### ISSUE TITLE
Update travis file after changes in Documenter.jl

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/GBIF.jl#12]
The documentation is not building (and the code coverage result are not sent to codecov)

**Comment by tpoisot** [comment]
#13 solves the coverage problem, let's see if the doc builds before closing

**Comment by mkborregaard** [comment]
You're right, sorry my close was premature

**Comment by tpoisot** [comment]
Everything is working but I need to re-generate the `DOCUMENTER_KEY`, will do so this evening.

**Comment by tpoisot** [comment]
:heavy_check_mark:
