### ISSUE TITLE
Paging after applying filters causes a bug in the number of records

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/GBIF.jl#15]
When calling `qualitycontrol!` followed by `next!`, the actual number of records is not counted correctly, which results in the wrong occurrences being returned. As the filters are not part of the `GBIFRecords` object (but this may be an improvement for a future version), the solution is most likely to call `showall!` when `next!` is called.

**Comment by mkborregaard** [comment]
In a sense `qualitycontrol!` is really just a synonym for `filter!`, right? Why not just use that?

**Comment by tpoisot** [comment]
I agree -- this is exactly what I'm doing at the moment!
