### ISSUE TITLE
The taxon function has no method to pass a taxon ID directly

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/GBIF.jl#17]
Currently, `taxon` performs only text search, but sometimes the ID of the taxon is known (for example, when we want the genus of a given species). This would require a second method.

The `taxon` function is defined here: https://github.com/EcoJulia/GBIF.jl/blob/master/src/taxon.jl

The GBIF API endpoint for taxa by ID is here: http://api.gbif.org/v1/species/216

**Comment by MichielStock** [comment]
@tpoisot Let's see if I can do this in half an hour!

**Comment by tpoisot** [comment]
:tada: make your PR on `master`, and @ me if you have questions!

**Comment by MichielStock** [comment]
I don't have much experience with querying a database:

- Should I write a function with method `taxon(taxonID::Int)` to indicate that we have a key?
- So the args would be `args = Dict{String, Any}("name" => 216, "strict" => strict, "verbose" => verbose)`
- line 68 
```julia
   sp_s_url = gbifurl * "species/match"
``` 
should then be 
```julia
   sp_s_url = gbifurl * "species"
```

This is how I understand it from the [API](https://www.gbif.org/developer/species#p_language), though the body which is collected always matches `WELP...`. 

Can you point me in the right direction?

**Comment by tpoisot** [comment]
@MichielStock the taxa informations are stored as a `Pair`: `name => id`, so maybe the function can have a method that accepts this. I would see two of them, in fact:

```julia
taxon(t::Pair) = taxon(t.second)
function taxon(id::Int)
 # general case with only the ID
end
```

And I think that in your example query, `name` should be `id`instead.

**Comment by MichielStock** [comment]
OK, seems to work, though the result of such a query does not have the keys `status`, `confidence` and `matchType`, which are required by `GBIFTaxon(o::Dict{String, Any})`.

I can either

- add default values for this
- make this optional for `GBIFTaxon`

**Comment by tpoisot** [comment]
@MichielStock can you open a pull request? I'll have a look at what the changes were, and can give better advice on `status`, etc.

By the way, please also add your name to the `.zenodo.json` file at the root of the project.
