### ISSUE TITLE
Tests for filtering sometimes fail

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/GBIF.jl#21]
My *best guess* as to why is: sometimes the most recent observations have no issues, and so the tests (which is testing the fact that the length before/after changes) are failing. This can be solved by putting a function which will remove some records *e.g.* at random, like `f(g::GBIFRecord) = rand() < 0.5`.

**Comment by mkborregaard** [comment]
will that not lead the tests to always pass?

**Comment by tpoisot** [comment]
The specific test is that after a filtering that removes some species, the length of the records object should be lower than before.
