### ISSUE TITLE
Use missing type when 1.0 is released

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/GBIF.jl#5]
Currently, a lot of fields in `Occurrence` are `Union{Whatever, Void}` -- it will make more sense to have the rely on `Missing`.

**Comment by mkborregaard** [comment]
Absolutely. Just curious - what does "blocked" mean?

**Comment by tpoisot** [comment]
Just that this is waiting on things we have no control over (here, the release of 1.0) -- just a note that I can't do anything about it now.

**Comment by tpoisot** [comment]
Closes #5 - solved by f27fcd2
